name: Close Pull Request

# only trigger on pull request closed events
on:
  pull_request:
    branches : 
      - main
    types: [ closed ]

runs:
  using: "composite"
  steps:    
    - run: pip install compliance-trestle
      shell: bash
      name: Install trestle

    
    - run: |
        echo $(ls)
        trestle assemble catalog -t
        trestle assemble profile -t
        trestle assemble target-definition -t
        trestle assemble component-definition -t
        trestle assemble system-security-plan -t
        trestle assemble assessment-plan -t
        trestle assemble assessment-results -t
        trestle assemble plan-of-action-and-milestones -t
      shell: bash
      name: Assemble
 
    - run: |
        git config --global user.name 'trestle-actions-bot'
        git config --global user.email 'trestle-bot@ibm.com'
        git add -A
        git commit -am "Automated assemble"
        git push origin main
      shell: bash
      name: Push commit

    
    - run:  |
        pip install python-semantic-release
        touch setup.cfg
        list=``
        filenames1=(`ls */*/*/metadata.json 2>/dev/null || true`)
        filenames2=(`ls */*/*.json 2>/dev/null || true`)
        filenames3=(`ls */*/*/metadata/*.json 2>/dev/null || true`)
        filenames4=(`ls dist/*/*.json 2>/dev/null || true`)
        allfiles=( "${filenames1[@]}" "${filenames2[@]}" "${filenames3[@]}" "${filenames4[@]}" )
        for eachfile in ${allfiles[@]}; do list="${list}$eachfile:\\\"version\\\": \"(\d+\.\d+\.\d+)\","; done
        echo $'[semantic_release]\nbranch = main\nbuild_command=\nupload_to_pypi=false\nremove_dist=false\nupload_to_release=True\nversion_source=commit\nversion_pattern ='"${list%?}">setup.cfg
        cat setup.cfg
        echo `ls`
        semantic-release publish
      
    - run: sudo ${{ github.action_path }}/goodbye.sh
      shell: bash
